# -*- coding: utf-8 -*-
"""netflix_dataanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6AP_Jp3teuKRW1GOgFzDSk57WS37PMa
"""

# import python libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt # visualizing data
import seaborn as sns

df = pd.read_csv('mymoviedb.csv', lineterminator='\n')

#display top 5 data
df.head()

#know the basic structure of the database
df.info()

#know the genre of the movies
df['Genre'].head()

#to get duplicated row, can also use df.duplicated().sum()
df.duplicated()

#get the statistics of data
df.describe()

"""Dataset

we have a dataframe consisting of 9827 rows and 9 columns.

• our dataset looks a bit tidy with no NaNs nor duplicated values.

• Release_Date column needs to be casted into date time and to extract only the

• Overview, Original_Languege and Poster-Url wouldn't be so useful during analys

• there is noticable outliers in Popularity column

• Vote_Average bettter be categorised for proper analysis.

• Genre column has comma saperated values and white spaces that needs to be hand
"""

df.head()

# Data Cleaning
# changing release_date format from yyyy-mm-dd to yyyy
df['Release_Date'] = pd.to_datetime(df['Release_Date'])
# confirming changes
print(df['Release_Date'].dtypes)

df['Release_Date'] = df['Release_Date'].dt.year
df['Release_Date'].dtypes

df.info()

df.head()

""" **Dropping Overview, Original_Languege
and Poster-Url**
"""

# making list of column to be dropped
cols = ['Overview', 'Original_Language', 'Poster_Url']
# dropping columns and confirming changes
df.drop(cols, axis = 1, inplace = True)
df.columns

df.head()

"""**Categorizing Vote_Average column**


We would cut the Vote_Average values and make 4 categories: popular average
below_avg not_popular to describe it more using catigorize_col() function
provided above.
"""

def catigorize_col (df, col, labels):
 """
 catigorizes a certain column based on its quartiles

 Args:
 (df) df - dataframe we are proccesing
 (col) str - to be catigorized column's name
 (labels) list - list of labels from min to max

 Returns:
 (df) df - dataframe with the categorized col
 """

 # setting the edges to cut the column accordingly
 edges = [df[col].describe()['min'],
          df[col].describe()['25%'],
          df[col].describe()['50%'],
          df[col].describe()['75%'],
          df[col].describe()['max']]
 df[col] = pd.cut(df[col], edges, labels = labels, duplicates='drop')
 return df

# define labels for edges
labels = ['not_popular', 'below_avg', 'average', 'popular']
# categorize column based on labels and edges
catigorize_col(df, 'Vote_Average', labels)
# confirming changes
df['Vote_Average'].unique()

df.head()

# exploring column
df['Vote_Average'].value_counts()

# dropping NaNs
df.dropna(inplace = True)

# confirming
df.isna().sum()

df.head()

"""we'd split genres into a list and then
explode our dataframe to have only one
genre per row for ezch movie
"""

# split the strings into lists
df['Genre'] = df['Genre'].str.split(', ')

# explode the lists
df = df.explode('Genre').reset_index(drop=True)
df.head()

# casting column into category
df['Genre'] = df['Genre'].astype('category')

# confirming changes
df['Genre'].dtypes

df.info()

df.nunique()

"""Now that our dataset is clean and tidy, we are left with a total of 6 columns and 25551
rows to dig into during our analysis

**Data Visualization**

Here, we'd use Matplotlib and seaborn for making some informative visuals to gain
insights abut our data
"""

# setting up seaborn configurations
sns.set_style('whitegrid')

# showing stats. on genre column
df['Genre'].describe()

# visualizing genre column
sns.catplot(y = 'Genre', data = df, kind = 'count',
 order = df['Genre'].value_counts().index,
 color = '#4287f5')
plt.title('genre column distribution')
plt.show()

"""we can notice from the above visual that Drama genre is the most frequent genre
in our dataset and has appeared more than 14% of the times among 19 other
genres
"""

# visualizing vote_average column
sns.catplot(y = 'Vote_Average', data = df, kind = 'count',
 order = df['Vote_Average'].value_counts().index,
 color = '#4287f5')
plt.title('votes destribution')
plt.show()

# checking max popularity in dataset
df[df['Popularity'] == df['Popularity'].max()]

# checking max popularity in dataset
df[df['Popularity'] == df['Popularity'].min()]

df['Release_Date'].hist()
plt.title('Release_Date column distribution')
plt.show()

"""**Conclusion**

1. Drama genre is the most frequent genre in our dataset and has appeared more than
14% of the times among 19 other genres.

2. We have 25.5% of our dataset with popular vote (6520 rows). Drama again gets the
highest popularity among fans by being having more than 18.5% of movies popularities.

3. Spider-Man: No Way Home has the highest popularity rate in our dataset and it has
genres of Action , Adventure and Sience Fiction .


4. The united states, thread' has the highest lowest rate in our dataset
and it has genres of music , drama , 'war', 'sci-fi' and history`.

5. Year 2020 has the highest filmming rate in our dataset
"""